# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EasiNet.Protocol.Control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import EasiNet.Protocol.Common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='EasiNet.Protocol.Control.proto',
  package='EasiNet.Network.Protocols',
  serialized_pb='\n\x1e\x45\x61siNet.Protocol.Control.proto\x12\x19\x45\x61siNet.Network.Protocols\x1a\x1d\x45\x61siNet.Protocol.Common.proto\"\x92\x01\n\nNetCommand\x12\x10\n\x08\x43lientId\x18\x01 \x02(\t\x12\x11\n\tContextId\x18\x02 \x02(\r\x12\r\n\x05Index\x18\x03 \x01(\x04\x12;\n\x0b\x43ommandType\x18\x04 \x02(\x0e\x32&.EasiNet.Network.Protocols.CommandEnum\x12\x13\n\x0b\x43ommandData\x18\x05 \x01(\x0c\"H\n\x1f\x43SAttenderConnectRequestCommand\x12\x12\n\nAttenderId\x18\x01 \x02(\t\x12\x11\n\tMeetingId\x18\x02 \x02(\t\"\xd2\x01\n SCAttenderConnectResponseCommand\x12;\n\tErrorCode\x18\x01 \x02(\x0e\x32(.EasiNet.Network.Protocols.ErrorCodeEnum\x12\x13\n\x0b\x41ttenderIds\x18\x02 \x03(\t\x12\x12\n\nSlideIndex\x18\x03 \x01(\x05\x12\x12\n\nSlideCount\x18\x04 \x01(\x05\x12\x34\n\x06Slides\x18\x05 \x03(\x0b\x32$.EasiNet.Network.Protocols.SlidePair\"2\n\x1c\x43SAttenderExitRequestCommand\x12\x12\n\nAttenderId\x18\x01 \x02(\t\"2\n\x1cSCAttenderInBroadcastCommand\x12\x12\n\nAttenderId\x18\x01 \x02(\t\":\n$SCAttenderDisconnectBroadcastCommand\x12\x12\n\nAttenderId\x18\x01 \x02(\t\"4\n\x1eSCAttendersOutBroadcastCommand\x12\x12\n\nAttenderId\x18\x01 \x02(\t\"\'\n\x14\x43SSlideRquestCommand\x12\x0f\n\x07SlideId\x18\x01 \x02(\t\"\x9f\x01\n\x15SCSlideReponseCommand\x12;\n\tErrorCode\x18\x01 \x02(\x0e\x32(.EasiNet.Network.Protocols.ErrorCodeEnum\x12\x0f\n\x07SlideId\x18\x02 \x02(\t\x12\x38\n\x08\x45lements\x18\x03 \x03(\x0b\x32&.EasiNet.Network.Protocols.ElementInfo\"a\n\x11SCResponseCommand\x12;\n\tErrorCode\x18\x01 \x02(\x0e\x32(.EasiNet.Network.Protocols.ErrorCodeEnum\x12\x0f\n\x07Reserve\x18\x02 \x01(\t')




_NETCOMMAND = _descriptor.Descriptor(
  name='NetCommand',
  full_name='EasiNet.Network.Protocols.NetCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ClientId', full_name='EasiNet.Network.Protocols.NetCommand.ClientId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ContextId', full_name='EasiNet.Network.Protocols.NetCommand.ContextId', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Index', full_name='EasiNet.Network.Protocols.NetCommand.Index', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CommandType', full_name='EasiNet.Network.Protocols.NetCommand.CommandType', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CommandData', full_name='EasiNet.Network.Protocols.NetCommand.CommandData', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=239,
)


_CSATTENDERCONNECTREQUESTCOMMAND = _descriptor.Descriptor(
  name='CSAttenderConnectRequestCommand',
  full_name='EasiNet.Network.Protocols.CSAttenderConnectRequestCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AttenderId', full_name='EasiNet.Network.Protocols.CSAttenderConnectRequestCommand.AttenderId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MeetingId', full_name='EasiNet.Network.Protocols.CSAttenderConnectRequestCommand.MeetingId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=241,
  serialized_end=313,
)


_SCATTENDERCONNECTRESPONSECOMMAND = _descriptor.Descriptor(
  name='SCAttenderConnectResponseCommand',
  full_name='EasiNet.Network.Protocols.SCAttenderConnectResponseCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrorCode', full_name='EasiNet.Network.Protocols.SCAttenderConnectResponseCommand.ErrorCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AttenderIds', full_name='EasiNet.Network.Protocols.SCAttenderConnectResponseCommand.AttenderIds', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SlideIndex', full_name='EasiNet.Network.Protocols.SCAttenderConnectResponseCommand.SlideIndex', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SlideCount', full_name='EasiNet.Network.Protocols.SCAttenderConnectResponseCommand.SlideCount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Slides', full_name='EasiNet.Network.Protocols.SCAttenderConnectResponseCommand.Slides', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=316,
  serialized_end=526,
)


_CSATTENDEREXITREQUESTCOMMAND = _descriptor.Descriptor(
  name='CSAttenderExitRequestCommand',
  full_name='EasiNet.Network.Protocols.CSAttenderExitRequestCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AttenderId', full_name='EasiNet.Network.Protocols.CSAttenderExitRequestCommand.AttenderId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=528,
  serialized_end=578,
)


_SCATTENDERINBROADCASTCOMMAND = _descriptor.Descriptor(
  name='SCAttenderInBroadcastCommand',
  full_name='EasiNet.Network.Protocols.SCAttenderInBroadcastCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AttenderId', full_name='EasiNet.Network.Protocols.SCAttenderInBroadcastCommand.AttenderId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=580,
  serialized_end=630,
)


_SCATTENDERDISCONNECTBROADCASTCOMMAND = _descriptor.Descriptor(
  name='SCAttenderDisconnectBroadcastCommand',
  full_name='EasiNet.Network.Protocols.SCAttenderDisconnectBroadcastCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AttenderId', full_name='EasiNet.Network.Protocols.SCAttenderDisconnectBroadcastCommand.AttenderId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=632,
  serialized_end=690,
)


_SCATTENDERSOUTBROADCASTCOMMAND = _descriptor.Descriptor(
  name='SCAttendersOutBroadcastCommand',
  full_name='EasiNet.Network.Protocols.SCAttendersOutBroadcastCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AttenderId', full_name='EasiNet.Network.Protocols.SCAttendersOutBroadcastCommand.AttenderId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=692,
  serialized_end=744,
)


_CSSLIDERQUESTCOMMAND = _descriptor.Descriptor(
  name='CSSlideRquestCommand',
  full_name='EasiNet.Network.Protocols.CSSlideRquestCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SlideId', full_name='EasiNet.Network.Protocols.CSSlideRquestCommand.SlideId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=746,
  serialized_end=785,
)


_SCSLIDEREPONSECOMMAND = _descriptor.Descriptor(
  name='SCSlideReponseCommand',
  full_name='EasiNet.Network.Protocols.SCSlideReponseCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrorCode', full_name='EasiNet.Network.Protocols.SCSlideReponseCommand.ErrorCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SlideId', full_name='EasiNet.Network.Protocols.SCSlideReponseCommand.SlideId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Elements', full_name='EasiNet.Network.Protocols.SCSlideReponseCommand.Elements', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=788,
  serialized_end=947,
)


_SCRESPONSECOMMAND = _descriptor.Descriptor(
  name='SCResponseCommand',
  full_name='EasiNet.Network.Protocols.SCResponseCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrorCode', full_name='EasiNet.Network.Protocols.SCResponseCommand.ErrorCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Reserve', full_name='EasiNet.Network.Protocols.SCResponseCommand.Reserve', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=949,
  serialized_end=1046,
)

_NETCOMMAND.fields_by_name['CommandType'].enum_type = EasiNet.Protocol.Common_pb2._COMMANDENUM
_SCATTENDERCONNECTRESPONSECOMMAND.fields_by_name['ErrorCode'].enum_type = EasiNet.Protocol.Common_pb2._ERRORCODEENUM
_SCATTENDERCONNECTRESPONSECOMMAND.fields_by_name['Slides'].message_type = EasiNet.Protocol.Common_pb2._SLIDEPAIR
_SCSLIDEREPONSECOMMAND.fields_by_name['ErrorCode'].enum_type = EasiNet.Protocol.Common_pb2._ERRORCODEENUM
_SCSLIDEREPONSECOMMAND.fields_by_name['Elements'].message_type = EasiNet.Protocol.Common_pb2._ELEMENTINFO
_SCRESPONSECOMMAND.fields_by_name['ErrorCode'].enum_type = EasiNet.Protocol.Common_pb2._ERRORCODEENUM
DESCRIPTOR.message_types_by_name['NetCommand'] = _NETCOMMAND
DESCRIPTOR.message_types_by_name['CSAttenderConnectRequestCommand'] = _CSATTENDERCONNECTREQUESTCOMMAND
DESCRIPTOR.message_types_by_name['SCAttenderConnectResponseCommand'] = _SCATTENDERCONNECTRESPONSECOMMAND
DESCRIPTOR.message_types_by_name['CSAttenderExitRequestCommand'] = _CSATTENDEREXITREQUESTCOMMAND
DESCRIPTOR.message_types_by_name['SCAttenderInBroadcastCommand'] = _SCATTENDERINBROADCASTCOMMAND
DESCRIPTOR.message_types_by_name['SCAttenderDisconnectBroadcastCommand'] = _SCATTENDERDISCONNECTBROADCASTCOMMAND
DESCRIPTOR.message_types_by_name['SCAttendersOutBroadcastCommand'] = _SCATTENDERSOUTBROADCASTCOMMAND
DESCRIPTOR.message_types_by_name['CSSlideRquestCommand'] = _CSSLIDERQUESTCOMMAND
DESCRIPTOR.message_types_by_name['SCSlideReponseCommand'] = _SCSLIDEREPONSECOMMAND
DESCRIPTOR.message_types_by_name['SCResponseCommand'] = _SCRESPONSECOMMAND

class NetCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NETCOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.NetCommand)

class CSAttenderConnectRequestCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CSATTENDERCONNECTREQUESTCOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.CSAttenderConnectRequestCommand)

class SCAttenderConnectResponseCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCATTENDERCONNECTRESPONSECOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.SCAttenderConnectResponseCommand)

class CSAttenderExitRequestCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CSATTENDEREXITREQUESTCOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.CSAttenderExitRequestCommand)

class SCAttenderInBroadcastCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCATTENDERINBROADCASTCOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.SCAttenderInBroadcastCommand)

class SCAttenderDisconnectBroadcastCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCATTENDERDISCONNECTBROADCASTCOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.SCAttenderDisconnectBroadcastCommand)

class SCAttendersOutBroadcastCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCATTENDERSOUTBROADCASTCOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.SCAttendersOutBroadcastCommand)

class CSSlideRquestCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CSSLIDERQUESTCOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.CSSlideRquestCommand)

class SCSlideReponseCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCSLIDEREPONSECOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.SCSlideReponseCommand)

class SCResponseCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCRESPONSECOMMAND

  # @@protoc_insertion_point(class_scope:EasiNet.Network.Protocols.SCResponseCommand)


# @@protoc_insertion_point(module_scope)
